name: Samples build

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - 'samples/**'
      - '.github/workflows/samples.yml'
  pull_request:
    branches: [main]
    paths:
      - 'samples/**'
      - '.github/workflows/samples.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: dotnet build
    steps:
      # region Build
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: samples/global.json

      - name: Build samples
        working-directory: samples
        run: dotnet build Samples.slnx -warnaserror --nologo
      # endregion
